### ISSUE TITLE
Wrong Parsec AMI name

### ISSUE THREAD

**Issue by pdesgarets** [cloudrig/CloudRIG#14]
Hi,
I wanted to use this tool, but cloudRig couldn't find Parsec images. Have the names recently changed ? Anyway, I tweaked it, using following `describeImages` argument 
```js
{
	Filters: [
		{
			Name: "name",
			Values: [config.AWSInstanceType === "g2.2xlarge" ? "g2*" : "g3*"]
		}
	],
	Owners : ["589318761596"]
}
```

I can PR if you think it's the right fix.

**Comment by aegixx** [comment]
Thanks @pdesgarets - this helped me get this running

**Comment by NitriKx** [comment]
As the parsec AMIs are not maintained I've started to build CloudRIG dedicated AMIs (https://github.com/cloudrig/CloudRIG-AWS-AMI).
Those are not using Parsec anymore but Rainway which is open source and seems to have a wider client panel. Therefore they are more opened to collaboration (as Parsec changes its business model and customer target).
